fields:
  mce_config:
    display: 'TinyMCE Settings'
    instructions: 'Accepts any <a href="https://www.tiny.cloud/docs/quick-start/" target="_blank" rel="noopener">TinyMCE 5x</a> configuration settings.'
    type: yaml
